# fly.toml app configuration file generated for myapp-damp-resonance-1475 on 2025-01-30T20:32:11+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'myapp-damp-resonance-1475'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
